config/routes.rb
HiddenGems3::Application.routes.draw do

  devise_for :users

 
  resources :videos do
    post 'vote_up'
    post 'vote_down'
  end
  

  get 'most_popular' => 'videos#most_popular'
  get 'top_48' => 'videos#top_48'
  root 'videos#top_48'
  get 'most_recent' => 'videos#most_recent'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  has_many :votes
  has_many :videos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
 acts_as_voteable
 belongs_to :user


 validates :artist, length: { maximum: 31, too_long: "%{count} characters is the maximum allowed" } 
 validates :song, length: { maximum: 31 }


  def self.text_search(query)
    if query.present?
 	    search(query)
    else
 	    scoped
    end
  end 	    	
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to root_url, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new', notice: 'Try again.' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  def vote_up
    current_user.vote_exclusively_for(@video = Video.find(params[:video_id]))
     
      respond_to do |format|
        format.html {redirect_to root_url}
        format.js  
        flash[:notice] = "Vote successfully created."

      end
  end          

  def vote_down
    begin
      current_user.vote_exclusively_against(@video = Video.find(params[:video_id]))
      flash[:notice] = "Vote successfully created."
      redirect_to root_url
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end                   
  
  def most_popular
    if params[:query]
      @search = 1
      @items = Video.all  
      @videos = Video.advanced_search(params[:query]).tally( :at_least => 1, :limit => 5, :order => 'vote_count desc').paginate(:page => params[:page], :per_page => 9)    
    else    
      @items = Video.all
      @videos = Video.tally( :at_least => 1, :limit => 5, :order => 'vote_count desc').paginate(:page => params[:page], :per_page => 9)  
    end
  end  

  def top_48
    if params[:query]
      @search = 1
      @items = Video.all  
      @videos = Video.advanced_search(params[:query]).tally( :at_least => 1, :limit => 5, :order => 'vote_count desc').paginate(:page => params[:page], :per_page => 9)  
    else    
      @items = Video.all
      @videos = Video.where(created_at: (Time.now.midnight - 2.day)..Time.now.midnight).tally( :at_least => 1, :limit => 5, :order => 'vote_count desc').paginate(:page => params[:page], :per_page => 9)
    end
  end  

  def most_recent
    if params[:query]
      @search = 1
      @items = Video.all  
      @videos = Video.advanced_search(params[:query]).tally( :at_least => 1, :limit => 5, :order => 'vote_count desc').paginate(:page => params[:page], :per_page => 9)  
    else    
      @items = Video.all
      @videos = Video.order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
    end    
  end  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
    params.require(:video).permit(:video_link, :song, :description,:submitted_by, :submitter_id, :artist)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if params[:query]
  	  @search = 1	
  	  @items = Video.all	
  	  @videos = Video.advanced_search(params[:query]).tally( :at_least => 1, :limit => 5, :order => 'vote_count desc').page(params[:page]).per_page(9)  
  	else
      @items = Video.all
      @videos = Video.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 9)
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def youtube_embed(youtube_url)
	if youtube_url[/youtu\.be\/([^\?]*)/]
	  youtube_id = $1
	else
	  # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
	  youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
	  youtube_id = $5
	end
	%Q{<iframe id="img-responsive" type="text/html" width="225" height="200"
	src="https://www.youtube.com/embed/#{youtube_id}?controls=1&showinfo=0&autohide=1&color=white&theme=light"
	frameborder="0" allowfullscreen></iframe>}
	end

	def youtube_comments(youtube_url)
	if youtube_url[/youtu\.be\/([^\?]*)/]
	  youtube_id = $1
	else
	  # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
	  youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
	  youtube_id = $5
	end
	%Q{<iframe id="img-responsive" type="text/html" width="520" height=300"
	src="https://www.youtube.com/embed/#{youtube_id}?controls=1&showinfo=0&autohide=1&color=white&theme=light"
	frameborder="0" allowfullscreen></iframe>}
	end
	
	def resource_class 
		User 
	end
	
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  
end

app/views/layouts/_navbar.html.erb
<div class= "container">
	<div class="navbar navbar-default navbar-fixed-top" >
		<%= render 'layouts/messages' %>


    <div class="navbar-collapse collapse">


		  <div class="navbar-header">
        <a href="/"><%= image_tag("logoym1.png")%></a>
      </div>
      
      <div class="nav navbar-nav navbar-left"><h1 style="color: #67ff5c; font-family: Leckerli One; font-size: 35px; margin-top: 10px; padding-right: 55px;"><a href="/" style="color: #ffffff; text-decoration: none;"> HiddenGems</h1></a></div>
          
      <form class="navbar-form navbar-left" role="search">
        
        <div class="form-group">
          <%= form_tag videos_path, class: "form-control",  method: :get do %>
          <%= text_field_tag :query, params[:query], class: "form-control" %>
        </div>
         <%= submit_tag "Search", class: "btn btn-default", :name => nil %>
        
        <% end %> 
      </form>  
  

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><h5 class="navbar-text" style="font-family: Petrona, serif; color: black; font-size: 20px;"><%= button_to "Submit a gem", new_video_path, :method => "get", class: "btn btn-sm btn-success" %></h5></li> 
          <li><h5 class="navbar-text", style="color: #ffffff; font-size: 20px;"><%= "@#{current_user.username}" %></li></h5>   
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right" style="display: inline;">
          <li><h5 class="navbar-text"><%= button_to "Create Account", new_user_registration_path, class: "btn btn-success", method: "get" %></li>
          <li><h5 class="navbar-text"><%= link_to "Sign in", user_session_path, method: "get", style: "color: #ffffff;" %></h5></li>
        </ul> 
      <% end %>
    </div>
	</div>
</div>  

app/views/new/create.html.erb
<h1>New#create</h1>
<p>Find me in app/views/new/create.html.erb</p>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.song %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/most_popular.html.erb
<div class="row col-md-1">
  <h3 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"><%= link_to "New", most_recent_path %></h3>
  <h3 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"><%= link_to "Rising", top_48_path %></h3>

  <% if user_signed_in? %>
    <h3 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"><%= link_to "Signout", destroy_user_session_path, :method => "delete"%></h3>
  <% else %>
  <% end %>  
</div>  
  <div class="row-fluid col-md-12">
    <div id="container-fluid">
      <div class="col-md-9 col-md-offset-1">
        <ul class="thumbnails list-unstyled item">
          <% if @search.nil? %>
            <h1 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"> Top </h1>
          <% else %>
            <h2 style="font-family: Leckerli One; color: black; ">Search Results</h2>      
          <% end%>

         <% @videos.each do |video| %>
            <div class="item" id="videos">
              <li class="col-md-4">
                <div class="thumbnail img-polaroid"> 
                  <%= raw youtube_embed(video.video_link)%>

                      <div class="voteup">
                        <% if current_user &&  current_user.voted_for?(@items.find(video.id))%>
                          <%= button_to "Thanks!", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm btn-success disabled", :remote => true %>
                        <% else %>
                          <%= button_to "Dope", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm  btn-success", :remote => true %>
                        <% end %>
                      </div>  
                      
                      <div class="votedown">
                        <% if current_user &&  current_user.voted_against?(@items.find(video.id)) %>
                          <%= button_to "Thanks!", video_vote_down_path(video.id), class: "btn btn-sm btn-danger disabled", style: "display: inline;", :remote => true %>
                        <% else %>
                          <%= button_to "Nope", video_vote_down_path(video.id), class: "btn btn-sm btn-danger", style: "display: inline;", :remote => true %>
                        <% end %>
                      </div>    

                    <div class="caption well">
                      <span><%= "Artist: #{video.artist}" %></span><br>
                      <%= "Song: #{video.song}"%><br>
                      <%= "Uncovered by: #{video.submitted_by}"%><br></span>
                      <em><%= "Votes: #{video.votes_for}"%></em><br></span>
                      <%= link_to "0 Comments", 
                      video_path(video, :anchor => "disqus_thread"), 
                     :"data-disqus-identifer" => video.id %><br>
                    </div>  
 
                </div>
              </li>               
            </div> 
          <% end %>
         </ul>
         <%= will_paginate @videos, style: "font-family: 'Tauri', sans-serif; font-size: 15px;" %>
      </div>
    </div>  
  </div>            

app/views/videos/most_recent.html.erb
<div class="row col-md-1">
  <h3 style="font-family: Leckerli One; color: black;"><%= link_to "Top 24hrs", top_24_path %></h3>
    <h3 style="font-family: Leckerli One; color: black;"><%= link_to "Most Popular", top_24_path %></h3>

  <% if user_signed_in? %>
    <h3 style="font-family: Leckerli One; color: lightblue;"><%= link_to "Signout", destroy_user_session_path, :method => "delete"%></h3>
  <% else %>
  <% end %>  
</div>  
  <div class="row-fluid col-md-12">
    <div id="container-fluid">
      <div class="col-md-10 col-md-offset-1">
        <ul class="thumbnails list-unstyled item">
          <% if @search.nil? %>
            <h1 style="font-family: Leckerli One; color: black; "> Most Recent </h1>
          <% else %>
            <h2 style="font-family: Leckerli One; color: black; ">Search Results</h2>      
          <% end%>

         <% @videos.each do |video| %>
            <div class="item" id="videos">
              <li class="col-md-4">
                <div class="thumbnail img-polaroid"> 
                  <%= raw youtube_embed(video.video_link)%>

                      <div class="voteup">
                        <% if current_user &&  current_user.voted_for?(@items.find(video.id))%>
                          <%= button_to "Thanks!", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm btn-success disabled", :remote => true %>
                        <% else %>
                          <%= button_to "Dope", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm  btn-success", :remote => true %>
                        <% end %>
                      </div>  
                      
                      <div class="votedown">
                        <% if current_user &&  current_user.voted_against?(@items.find(video.id)) %>
                          <%= button_to "Thanks!", video_vote_down_path(video.id), class: "btn btn-sm btn-danger disabled", style: "display: inline;", :remote => true %>
                        <% else %>
                          <%= button_to "Nope", video_vote_down_path(video.id), class: "btn btn-sm btn-danger", style: "display: inline;", :remote => true %>
                        <% end %>
                      </div>    

                    <div class="caption well">
                      <span><%= "Artist: #{video.artist}" %></span><br>
                      <%= "Song: #{video.song}"%><br>
                      <%= "Uncovered by: #{video.submitted_by}"%><br></span>
                      <em><%= "Votes: #{video.votes_for}"%></em><br></span>
                      <%= link_to "0 Comments", 
                      video_path(video, :anchor => "disqus_thread"), 
                     :"data-disqus-identifer" => video.id %><br>
                    </div>  
 
                </div>
              </li>               
            </div> 
          <% end %>
         </ul>
         <%= will_paginate @videos, style: "font-family: 'Tauri', sans-serif; font-size: 15px;" %>
      </div>
    </div>  
  </div>            

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="container">
	<div class="row col-md-6  col-md-offset-3">


	<p id="notice"><%= notice %></p>

	  <div class="commentsvideo">
	    <%= raw youtube_comments(@video.video_link) %>
	  </div>

	<div id="disqus_thread"></div>
	    <script type="text/javascript">
	        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	        var disqus_shortname = 'hiddengems100'; // required: replace example with your forum shortname

	        /* * * DON'T EDIT BELOW THIS LINE * * */
	        (function() {
	            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
	            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	        })();
	    </script>
	    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


	<%= link_to 'Edit', edit_video_path(@video) %> |
	<%= link_to 'Back', videos_path %>
  </div>
</div>	

app/views/videos/top_24.html.erb
<div class="row col-md-1">
  <h3 style="font-family: 'Tauri', sans-serif; color: lightblue;"><%= link_to "Most Recent", most_recent_path %></h3>
  <h3 style="font-family: 'Tauri', sans-serif; lightblue;"><%= link_to "Most Popular", most_popular_path %></h3>
  <% if user_signed_in? %>
    <h3 style="font-family: 'Tauri', sans-serif; color: lightblue;"><%= link_to "Signout", destroy_user_session_path, :method => "delete"%></h3>
  <% else %>
  <% end %>  
</div>  
  <div class="row-fluid col-md-12">
    <div id="container-fluid">
      <div class="col-md-10 col-md-offset-1">
        <ul class="thumbnails list-unstyled item">
          <% if @search.nil? %>
            <h1 style="font-family: 'Tauri', sans-serif; color: black; "> Top in 24 hours </h1>
          <% else %>
            <h2 style="font-family: Leckerli One; color: black; ">Search Results</h2>      
          <% end%>

          <% @videos.each do |video| %>
            <div class="item" id="videos">
              <li class="col-md-4">
                <div class="thumbnail img-polaroid"> 
                  <%= raw youtube_embed(video.video_link)%>

                      <div class="voteup">
                        <% if current_user &&  current_user.voted_for?(@items.find(video.id))%>
                          <%= button_to "Thanks!", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm btn-success disabled", :remote => true %>
                        <% else %>
                          <%= button_to "Dope", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm  btn-success", :remote => true %>
                        <% end %>
                      </div>  
                      
                      <div class="votedown">
                        <% if current_user &&  current_user.voted_against?(@items.find(video.id)) %>
                          <%= button_to "Thanks!", video_vote_down_path(video.id), class: "btn btn-sm btn-danger disabled", style: "display: inline;", :remote => true %>
                        <% else %>
                          <%= button_to "Nope", video_vote_down_path(video.id), class: "btn btn-sm btn-danger", style: "display: inline;", :remote => true %>
                        <% end %>
                      </div>    

                    <div class="caption well">
                      <span><%= "Artist: #{video.artist}" %></span><br>
                      <%= "Song: #{video.song}"%><br>
                      <%= "Uncovered by: #{video.submitted_by}"%><br></span>
                      <em><%= "Votes: #{video.votes_for}"%></em><br></span>
                      <%= link_to "0 Comments", 
                      video_path(video, :anchor => "disqus_thread"), 
                     :"data-disqus-identifer" => video.id %><br>
                    </div>  
 
                </div>
              </li>               
            </div> 
          <% end %>
         </ul>
         <%= will_paginate @videos, style: "font-family: 'Tauri', sans-serif; font-size: 15px;" %>
      </div>
    </div>  
  </div>            

app/views/videos/top_48.html.erb
<div class="row col-md-1">
  <h3 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"><%= link_to "New", most_recent_path %></h3>
    <h3 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"><%= link_to "Top", most_popular_path %></h3>

  <% if user_signed_in? %>
    <h3 style="font-family: 'Fredoka One', cursive; color: black; font-size: 20px;"><%= link_to "Signout", destroy_user_session_path, :method => "delete"%></h3>
  <% else %>
  <% end %>  
</div>  
  <div class="row-fluid col-md-12">
    <div id="container-fluid">
      <div class="col-md-9 col-md-offset-1">
        <ul class="thumbnails list-unstyled item">
          <% if @search.nil? %>
            <h1 style="font-size: 20px; font-family: 'Fredoka One', cursive; color: black; "> Rising </h1>
          <% else %>
            <h2 style="font-size: 10px; font-family: Leckerli One; color: black; ">Search Results</h2>      
          <% end%>

          <% @videos.each do |video| %>
            <div class="item" id="videos">
              <li class="col-md-4">
                <div class="thumbnail img-polaroid"> 
                  <%= raw youtube_embed(video.video_link)%>

                      <div class="voteup">
                        <% if current_user &&  current_user.voted_for?(@items.find(video.id))%>
                          <%= button_to "Thanks!", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm btn-success disabled", :remote => true %>
                        <% else %>
                          <%= button_to "Dope", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm  btn-success", :remote => true %>
                        <% end %>
                      </div>  
                      
                      <div class="votedown">
                        <% if current_user &&  current_user.voted_against?(@items.find(video.id)) %>
                          <%= button_to "Thanks!", video_vote_down_path(video.id), class: "btn btn-sm btn-danger disabled", style: "display: inline;", :remote => true %>
                        <% else %>
                          <%= button_to "Nope", video_vote_down_path(video.id), class: "btn btn-sm btn-danger", style: "display: inline;", :remote => true %>
                        <% end %>
                      </div>    

                    <div class="caption well">
                      <span><%= "Artist: #{video.artist}" %></span><br>
                      <%= "Song: #{video.song}"%><br>
                      <%= "Uncovered by: #{video.submitted_by}"%><br></span>
                      <em><%= "Votes: #{video.votes_for}"%></em><br></span>
                      <%= link_to "0 Comments", 
                      video_path(video, :anchor => "disqus_thread"), 
                     :"data-disqus-identifer" => video.id %><br>
                    </div>  
 
                </div>
              </li>               
            </div> 
          <% end %>
         </ul>
         <%= will_paginate @videos, style: "font-family: 'Tauri', sans-serif; font-size: 15px;" %>
      </div>
    </div>  
  </div>            

app/views/welcome/index.html.erb
  
<div class="row col-md-1">
  <h3 style="font-family: Leckerli One; color: lightblue;"><%= link_to "Most Popular", most_popular_path %></h3>
  <% if user_signed_in? %>
    <h3 style="font-family: Leckerli One; color: lightblue;"><%= link_to "Signout", destroy_user_session_path, :method => "delete"%></h3>
  <% else %>
  <% end %>  
</div>  
  <div class="row-fluid col-md-12">
    <div id="container-fluid">
      <div class="col-md-10 col-md-offset-1">
        <ul class="thumbnails list-unstyled item">
          <% if @search.nil? %>
            <h1 style="font-family: Leckerli One; color: black; "> Most Recent </h1>
          <% else %>
            <h2 style="font-family: Leckerli One; color: black; ">Search Results</h2>      
          <% end%>

          <% @videos.each do |video| %>
            <div class="item" id="videos">
              <li class="col-md-4">
                <div class="thumbnail img-polaroid"> 
                  <%= raw youtube_embed(video.video_link)%>

                      <div class="voteup">
                        <% if current_user &&  current_user.voted_for?(@items.find(video.id))%>
                          <%= button_to "Thanks!", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm btn-success disabled", :remote => true %>
                        <% else %>
                          <%= button_to "Dope", video_vote_up_path(video.id), id: "voteup", class: "btn btn-sm  btn-success", :remote => true %>
                        <% end %>
                      </div>  
                      
                      <div class="votedown">
                        <% if current_user &&  current_user.voted_against?(@items.find(video.id)) %>
                          <%= button_to "Thanks!", video_vote_down_path(video.id), class: "btn btn-sm btn-danger disabled", style: "display: inline;", :remote => true %>
                        <% else %>
                          <%= button_to "Nope", video_vote_down_path(video.id), class: "btn btn-sm btn-danger", style: "display: inline;", :remote => true %>
                        <% end %>
                      </div>    

                    <div class="caption well">
                      <span><%= "Artist: #{video.artist}" %></span><br>
                      <%= "Song: #{video.song}"%><br>
                      <%= "Uncovered by: #{video.submitted_by}"%><br></span>
                      <em><%= "Votes: #{video.votes_for}"%></em><br></span>
                      <%= link_to "0 Comments", 
                      video_path(video, :anchor => "disqus_thread"), 
                     :"data-disqus-identifer" => video.id %><br>
                    </div>  
 
                </div>
              </li>               
            </div> 
          <% end %>
         </ul>
         <%= will_paginate @videos, style: "font-family: 'Tauri', sans-serif; font-size: 15px;" %>
      </div>
    </div>  
  </div>            